name: Robot Framework Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/piilo/hsl-demo/ta_base_image:latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute tests
        run: robot -d results/    tests/tests.robot
      - name: Publish results
        uses: actions/upload-artifact@v4
        with:
            name: reports
            path: results
            retention-days: 7