name: Robot Framework Tests
on:
  push:
    branches:
      - 'main'
    paths:
      - 'tests/tests.robot'
jobs:
  Run_tests_and_create_report:
    runs-on: ubuntu-latest
    container: ghcr.io/piilo/hsl-demo/ta_base_image:latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Run Robot Framework tests
        env:
          DD_API_KEY: ${{secrets.DD_API_KEY}}
        run: robot -d results/ -v BROWSER:${{vars.BROWSER}} --listener allure_robotframework:allure-results tests/tests.robot
      - name: Save environment info
        if: always()
        continue-on-error: true
        run: |
          echo "Browser = ${{vars.BROWSER}}" > allure-results/environment.properties
          echo Robot_Framework = $(robot --version) >> allure-results/environment.properties
          echo OS = $(cat /etc/issue) >> allure-results/environment.properties
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results
          allure_report: allure-report
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: reports
            path: results
            retention-days: 60