name: Robot Framework Tests
on:
  schedule:
    - cron:  '30 18 * * 2'
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/piilo/hsl-demo/ta_base_image:latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute tests
        env:
          DD_API_KEY: ${{secrets.DD_API_KEY}}
        run: robot -d results/    tests/tests.robot
      - name: Publish results
        uses: actions/upload-artifact@v4
        with:
            name: reports
            path: results
            retention-days: 7